# Generated by Django 5.1a1 on 2024-06-12 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='unaapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='GlucoseMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=50)),
                ('device_timestamp', models.DateTimeField()),
                ('recording_type', models.PositiveIntegerField(choices=[('0', 'Type 0'), ('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3'), ('4', 'Type 4'), ('5', 'Type 5'), ('6', 'Type 6')])),
                ('glucose_value_ml', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-1), django.core.validators.MaxLengthValidator(limit_value=300)])),
                ('glucose_scan_ml', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=-1), django.core.validators.MaxLengthValidator(limit_value=300)])),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='unaapp.userreport')),
            ],
        ),
    ]
