# Generated by Django 5.1a1 on 2024-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unaapp', '0001_create_all_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosemetric',
            name='glucose_scan_ml',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='glucosemetric',
            name='glucose_value_ml',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
